
//  ==> COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class AbstractAdditionalLogger : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AbstractAdditionalLogger(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractAdditionalLogger obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbstractAdditionalLogger() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_AbstractAdditionalLogger(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual bool logLevel(JournalLogLevel level) {
    bool ret = xsensdeviceapiPINVOKE.AbstractAdditionalLogger_logLevel__SWIG_0(swigCPtr, (int)level);
    return ret;
  }

  public virtual JournalLogLevel logLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.AbstractAdditionalLogger_logLevel__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual JournalLogLevel debugLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.AbstractAdditionalLogger_debugLevel(swigCPtr);
    return ret;
  }

  public virtual void setLogLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.AbstractAdditionalLogger_setLogLevel(swigCPtr, (int)level);
  }

  public virtual void setDebugLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.AbstractAdditionalLogger_setDebugLevel(swigCPtr, (int)level);
  }

  public virtual void log(JournalLogLevel level, string file, int line, string function, string msg) {
    xsensdeviceapiPINVOKE.AbstractAdditionalLogger_log(swigCPtr, (int)level, file, line, function, msg);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void logNoDecoration(JournalLogLevel level, string file, int line, string function, string msg) {
    xsensdeviceapiPINVOKE.AbstractAdditionalLogger_logNoDecoration(swigCPtr, (int)level, file, line, function, msg);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public AbstractAdditionalLogger() : this(xsensdeviceapiPINVOKE.new_AbstractAdditionalLogger(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("logLevel", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateAbstractAdditionalLogger_0(SwigDirectorMethodlogLevel__SWIG_0);
    if (SwigDerivedClassHasMethod("logLevel", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateAbstractAdditionalLogger_1(SwigDirectorMethodlogLevel__SWIG_1);
    if (SwigDerivedClassHasMethod("debugLevel", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateAbstractAdditionalLogger_2(SwigDirectorMethoddebugLevel);
    if (SwigDerivedClassHasMethod("setLogLevel", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateAbstractAdditionalLogger_3(SwigDirectorMethodsetLogLevel);
    if (SwigDerivedClassHasMethod("setDebugLevel", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateAbstractAdditionalLogger_4(SwigDirectorMethodsetDebugLevel);
    if (SwigDerivedClassHasMethod("log", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateAbstractAdditionalLogger_5(SwigDirectorMethodlog);
    if (SwigDerivedClassHasMethod("logNoDecoration", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateAbstractAdditionalLogger_6(SwigDirectorMethodlogNoDecoration);
    xsensdeviceapiPINVOKE.AbstractAdditionalLogger_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(AbstractAdditionalLogger));
    return hasDerivedMethod;
  }

  private bool SwigDirectorMethodlogLevel__SWIG_0(int level) {
    return logLevel((JournalLogLevel)level);
  }

  private int SwigDirectorMethodlogLevel__SWIG_1() {
    return (int)logLevel();
  }

  private int SwigDirectorMethoddebugLevel() {
    return (int)debugLevel();
  }

  private void SwigDirectorMethodsetLogLevel(int level) {
    setLogLevel((JournalLogLevel)level);
  }

  private void SwigDirectorMethodsetDebugLevel(int level) {
    setDebugLevel((JournalLogLevel)level);
  }

  private void SwigDirectorMethodlog(int level, string file, int line, string function, string msg) {
    log((JournalLogLevel)level, file, line, function, msg);
  }

  private void SwigDirectorMethodlogNoDecoration(int level, string file, int line, string function, string msg) {
    logNoDecoration((JournalLogLevel)level, file, line, function, msg);
  }

  public delegate bool SwigDelegateAbstractAdditionalLogger_0(int level);
  public delegate int SwigDelegateAbstractAdditionalLogger_1();
  public delegate int SwigDelegateAbstractAdditionalLogger_2();
  public delegate void SwigDelegateAbstractAdditionalLogger_3(int level);
  public delegate void SwigDelegateAbstractAdditionalLogger_4(int level);
  public delegate void SwigDelegateAbstractAdditionalLogger_5(int level, string file, int line, string function, string msg);
  public delegate void SwigDelegateAbstractAdditionalLogger_6(int level, string file, int line, string function, string msg);

  private SwigDelegateAbstractAdditionalLogger_0 swigDelegate0;
  private SwigDelegateAbstractAdditionalLogger_1 swigDelegate1;
  private SwigDelegateAbstractAdditionalLogger_2 swigDelegate2;
  private SwigDelegateAbstractAdditionalLogger_3 swigDelegate3;
  private SwigDelegateAbstractAdditionalLogger_4 swigDelegate4;
  private SwigDelegateAbstractAdditionalLogger_5 swigDelegate5;
  private SwigDelegateAbstractAdditionalLogger_6 swigDelegate6;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(JournalLogLevel) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(JournalLogLevel) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(JournalLogLevel) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(JournalLogLevel), typeof(string), typeof(int), typeof(string), typeof(string) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(JournalLogLevel), typeof(string), typeof(int), typeof(string), typeof(string) };
}

}
