
//  ==> COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class AdditionalLoggerBase : AbstractAdditionalLogger {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AdditionalLoggerBase(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.AdditionalLoggerBase_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AdditionalLoggerBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_AdditionalLoggerBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public AdditionalLoggerBase(JournalLogLevel initialLogLevel) : this(xsensdeviceapiPINVOKE.new_AdditionalLoggerBase__SWIG_0((int)initialLogLevel), true) {
    SwigDirectorConnect();
  }

  public AdditionalLoggerBase() : this(xsensdeviceapiPINVOKE.new_AdditionalLoggerBase__SWIG_1(), true) {
    SwigDirectorConnect();
  }

  public override JournalLogLevel logLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.AdditionalLoggerBase_logLevel__SWIG_0(swigCPtr);
    return ret;
  }

  public override JournalLogLevel debugLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.AdditionalLoggerBase_debugLevel(swigCPtr);
    return ret;
  }

  public override void setLogLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.AdditionalLoggerBase_setLogLevel(swigCPtr, (int)level);
  }

  public override void setDebugLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.AdditionalLoggerBase_setDebugLevel(swigCPtr, (int)level);
  }

  public override bool logLevel(JournalLogLevel level) {
    bool ret = xsensdeviceapiPINVOKE.AdditionalLoggerBase_logLevel__SWIG_1(swigCPtr, (int)level);
    return ret;
  }

  public override void logNoDecoration(JournalLogLevel level, string file, int line, string function, string msg) {
    if (SwigDerivedClassHasMethod("logNoDecoration", swigMethodTypes1)) xsensdeviceapiPINVOKE.AdditionalLoggerBase_logNoDecorationSwigExplicitAdditionalLoggerBase(swigCPtr, (int)level, file, line, function, msg); else xsensdeviceapiPINVOKE.AdditionalLoggerBase_logNoDecoration(swigCPtr, (int)level, file, line, function, msg);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  protected virtual void onLogLevelChanged(JournalLogLevel newLevel, JournalLogLevel oldLevel) {
    if (SwigDerivedClassHasMethod("onLogLevelChanged", swigMethodTypes2)) xsensdeviceapiPINVOKE.AdditionalLoggerBase_onLogLevelChangedSwigExplicitAdditionalLoggerBase(swigCPtr, (int)newLevel, (int)oldLevel); else xsensdeviceapiPINVOKE.AdditionalLoggerBase_onLogLevelChanged(swigCPtr, (int)newLevel, (int)oldLevel);
  }

  protected virtual void onDebugLevelChanged(JournalLogLevel newLevel, JournalLogLevel oldLevel) {
    if (SwigDerivedClassHasMethod("onDebugLevelChanged", swigMethodTypes3)) xsensdeviceapiPINVOKE.AdditionalLoggerBase_onDebugLevelChangedSwigExplicitAdditionalLoggerBase(swigCPtr, (int)newLevel, (int)oldLevel); else xsensdeviceapiPINVOKE.AdditionalLoggerBase_onDebugLevelChanged(swigCPtr, (int)newLevel, (int)oldLevel);
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("log", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateAdditionalLoggerBase_0(SwigDirectorMethodlog);
    if (SwigDerivedClassHasMethod("logNoDecoration", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateAdditionalLoggerBase_1(SwigDirectorMethodlogNoDecoration);
    if (SwigDerivedClassHasMethod("onLogLevelChanged", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateAdditionalLoggerBase_2(SwigDirectorMethodonLogLevelChanged);
    if (SwigDerivedClassHasMethod("onDebugLevelChanged", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateAdditionalLoggerBase_3(SwigDirectorMethodonDebugLevelChanged);
    xsensdeviceapiPINVOKE.AdditionalLoggerBase_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(AdditionalLoggerBase));
    return hasDerivedMethod;
  }

  private void SwigDirectorMethodlog(int level, string file, int line, string function, string msg) {
    log((JournalLogLevel)level, file, line, function, msg);
  }

  private void SwigDirectorMethodlogNoDecoration(int level, string file, int line, string function, string msg) {
    logNoDecoration((JournalLogLevel)level, file, line, function, msg);
  }

  private void SwigDirectorMethodonLogLevelChanged(int newLevel, int oldLevel) {
    onLogLevelChanged((JournalLogLevel)newLevel, (JournalLogLevel)oldLevel);
  }

  private void SwigDirectorMethodonDebugLevelChanged(int newLevel, int oldLevel) {
    onDebugLevelChanged((JournalLogLevel)newLevel, (JournalLogLevel)oldLevel);
  }

  public delegate void SwigDelegateAdditionalLoggerBase_0(int level, string file, int line, string function, string msg);
  public delegate void SwigDelegateAdditionalLoggerBase_1(int level, string file, int line, string function, string msg);
  public delegate void SwigDelegateAdditionalLoggerBase_2(int newLevel, int oldLevel);
  public delegate void SwigDelegateAdditionalLoggerBase_3(int newLevel, int oldLevel);

  private SwigDelegateAdditionalLoggerBase_0 swigDelegate0;
  private SwigDelegateAdditionalLoggerBase_1 swigDelegate1;
  private SwigDelegateAdditionalLoggerBase_2 swigDelegate2;
  private SwigDelegateAdditionalLoggerBase_3 swigDelegate3;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(JournalLogLevel), typeof(string), typeof(int), typeof(string), typeof(string) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(JournalLogLevel), typeof(string), typeof(int), typeof(string), typeof(string) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(JournalLogLevel), typeof(JournalLogLevel) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(JournalLogLevel), typeof(JournalLogLevel) };
}

}
