
//  ==> COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE <==
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO AN END USER LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  
//  THIS SOFTWARE CAN CONTAIN OPEN SOURCE COMPONENTS WHICH CAN BE SUBJECT TO 
//  THE FOLLOWING GENERAL PUBLIC LICENSES:
//  ==> Qt GNU LGPL version 3: http://doc.qt.io/qt-5/lgpl.html <==
//  ==> LAPACK BSD License:  http://www.netlib.org/lapack/LICENSE.txt <==
//  ==> StackWalker 3-Clause BSD License: https://github.com/JochenKalmbach/StackWalker/blob/master/LICENSE <==
//  ==> Icon Creative Commons 3.0: https://creativecommons.org/licenses/by/3.0/legalcode <==
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public class Journaller : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Journaller(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Journaller obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Journaller() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_Journaller(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Journaller(XsString pathfile, bool purge, JournalLogLevel initialLogLevel) : this(xsensdeviceapiPINVOKE.new_Journaller__SWIG_0(XsString.getCPtr(pathfile), purge, (int)initialLogLevel), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Journaller(XsString pathfile, bool purge) : this(xsensdeviceapiPINVOKE.new_Journaller__SWIG_1(XsString.getCPtr(pathfile), purge), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Journaller(XsString pathfile) : this(xsensdeviceapiPINVOKE.new_Journaller__SWIG_2(XsString.getCPtr(pathfile)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void log(JournalLogLevel level, string msg) {
    xsensdeviceapiPINVOKE.Journaller_log(swigCPtr, (int)level, msg);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeCallstack(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.Journaller_writeCallstack(swigCPtr, (int)level);
  }

  public void setLogLevel(JournalLogLevel level, bool writeLogLine) {
    xsensdeviceapiPINVOKE.Journaller_setLogLevel__SWIG_0(swigCPtr, (int)level, writeLogLine);
  }

  public void setLogLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.Journaller_setLogLevel__SWIG_1(swigCPtr, (int)level);
  }

  public JournalLogLevel logLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.Journaller_logLevel__SWIG_0(swigCPtr);
    return ret;
  }

  public bool logLevel(JournalLogLevel level) {
    bool ret = xsensdeviceapiPINVOKE.Journaller_logLevel__SWIG_1(swigCPtr, (int)level);
    return ret;
  }

  public void setDebugLevel(JournalLogLevel level, bool writeLogLine) {
    xsensdeviceapiPINVOKE.Journaller_setDebugLevel__SWIG_0(swigCPtr, (int)level, writeLogLine);
  }

  public void setDebugLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.Journaller_setDebugLevel__SWIG_1(swigCPtr, (int)level);
  }

  public JournalLogLevel debugLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.Journaller_debugLevel(swigCPtr);
    return ret;
  }

  public void setFlushLevel(JournalLogLevel level, bool writeLogLine) {
    xsensdeviceapiPINVOKE.Journaller_setFlushLevel__SWIG_0(swigCPtr, (int)level, writeLogLine);
  }

  public void setFlushLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.Journaller_setFlushLevel__SWIG_1(swigCPtr, (int)level);
  }

  public JournalLogLevel flushLevel() {
    JournalLogLevel ret = (JournalLogLevel)xsensdeviceapiPINVOKE.Journaller_flushLevel(swigCPtr);
    return ret;
  }

  public void writeFileHeader(string appName) {
    xsensdeviceapiPINVOKE.Journaller_writeFileHeader(swigCPtr, appName);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setUseDateTime(bool yes) {
    xsensdeviceapiPINVOKE.Journaller_setUseDateTime(swigCPtr, yes);
  }

  public void writeTime() {
    xsensdeviceapiPINVOKE.Journaller_writeTime(swigCPtr);
  }

  public void writeThread() {
    xsensdeviceapiPINVOKE.Journaller_writeThread(swigCPtr);
  }

  public void writeTag() {
    xsensdeviceapiPINVOKE.Journaller_writeTag(swigCPtr);
  }

  public void writeLevel(JournalLogLevel level) {
    xsensdeviceapiPINVOKE.Journaller_writeLevel(swigCPtr, (int)level);
  }

  public void writeMessage(string msg) {
    xsensdeviceapiPINVOKE.Journaller_writeMessage(swigCPtr, msg);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void flush() {
    xsensdeviceapiPINVOKE.Journaller_flush(swigCPtr);
  }

  public void cleanupThread() {
    xsensdeviceapiPINVOKE.Journaller_cleanupThread(swigCPtr);
  }

  public XsString filename() {
    XsString ret = new XsString(xsensdeviceapiPINVOKE.Journaller_filename(swigCPtr), true);
    return ret;
  }

  public void setTag(string tag) {
    xsensdeviceapiPINVOKE.Journaller_setTag(swigCPtr, tag);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public string tag() {
    string ret = xsensdeviceapiPINVOKE.Journaller_tag(swigCPtr);
    return ret;
  }

  public static void setAdditionalLogger(AbstractAdditionalLogger additionalLogger) {
    xsensdeviceapiPINVOKE.Journaller_setAdditionalLogger(AbstractAdditionalLogger.getCPtr(additionalLogger));
  }

  public static bool hasAdditionalLogger() {
    bool ret = xsensdeviceapiPINVOKE.Journaller_hasAdditionalLogger();
    return ret;
  }

  public static AbstractAdditionalLogger additionalLogger() {
    global::System.IntPtr cPtr = xsensdeviceapiPINVOKE.Journaller_additionalLogger();
    AbstractAdditionalLogger ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractAdditionalLogger(cPtr, false);
    return ret;
  }

  public static string tagFromFilename(string fn) {
    string ret = xsensdeviceapiPINVOKE.Journaller_tagFromFilename(fn);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void moveLogFile(XsString pathfile, bool purge, bool eraseOld) {
    xsensdeviceapiPINVOKE.Journaller_moveLogFile__SWIG_0(swigCPtr, XsString.getCPtr(pathfile), purge, eraseOld);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void moveLogFile(XsString pathfile, bool purge) {
    xsensdeviceapiPINVOKE.Journaller_moveLogFile__SWIG_1(swigCPtr, XsString.getCPtr(pathfile), purge);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void moveLogFile(XsString pathfile) {
    xsensdeviceapiPINVOKE.Journaller_moveLogFile__SWIG_2(swigCPtr, XsString.getCPtr(pathfile));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void moveLogs(Journaller target, bool eraseOld) {
    xsensdeviceapiPINVOKE.Journaller_moveLogs__SWIG_0(swigCPtr, Journaller.getCPtr(target), eraseOld);
  }

  public void moveLogs(Journaller target) {
    xsensdeviceapiPINVOKE.Journaller_moveLogs__SWIG_1(swigCPtr, Journaller.getCPtr(target));
  }

}

}
